function checkSafety(llmResponse) {
  const flags = ["emergency", "suicide", "bleeding profusely", "can't breathe", "chest pain", "hospital"];
  const lowerResponse = llmResponse.toLowerCase();
  
  let isEscalated = false;
  let reason = "None";

  for (let flag of flags) {
    if (lowerResponse.includes(flag)) {
      isEscalated = true;
      reason = `Safety Rule Engine caught flagged keyword generated by LLM: ${flag}`;
      break;
    }
  }

  // Pre-process check
  if(isEscalated) {
      return {
          safe: false,
          escalationReason: reason,
          fallbackMessage: "I want to make sure you are safe. I have flagged this to the physician immediately. If this is an emergency, please visit the nearest hospital or call emergency services."
      }
  }

  return { safe: true };
}

module.exports = { checkSafety };
